@startuml class

class RenCService << localhost:5001, Application >> {
}

class CarProviders << Controller >> {
    {method} + <<GET>>  getCarProviders()
    {method} + <<POST>> createCarProvider()
}

class CarProvidersID << Controller >> {
    {method} + <<GET>>  getCarProvider()
    {method} + <<PUT>>  updateCarProvider()
    {method} + <<DELETE>>  deleteCarProvider()
}

class CarProvider << Resource >> {
    {field} + name
    {field} + address
    {field} + tel

    {method} + find ()
    {method} + findById()
    {method} + create()
    {method} + findByIdAndUpdate()
    {method} + remove()
}


class Auth << Controller >> {
    {method} + <<POST>> register()
    {method} + <<POST>> login()
    {method} + <<GET>> getMe()
    {method} + <<GET>> logout()
    {method} - sendTokenResponse()
}

class User << Resource >> {
    {field} + name
    {field} + email
    {field} + tel
    {field} + role
    {field} + password

    {method} + create()
    {method} + findOne()
    {method} + findById()
    {method} + getSignedJwtToken()
    {method} + matchPassword()
}

class Rentals << Controller >> {
    {method} + <<GET>> getRentals()
    {method} + <<POST>> addRental()
}

class RentalsID << Controller >> {
    {method} + <<GET>> getRental()
    {method} + <<PUT>> updateRental()
    {method} + <<DELETE>> deleteRental()
}

class Rental << Resource >> {
    {field} + startRentDate
    {field} + endRentDate
    {field} + user
    {field} + carProviders
    {field} + createdAt

    {method} + find ()
    {method} + findById()
    {method} + create()
    {method} + findByIdAndUpdate()
    {method} + remove()
}

class Middleware {
    {method} + protect()
    {method} + authorize()
}

RenCService ..> CarProviders : <<ResourcePath>>\n/carproviders
CarProviders ..> CarProvider

RenCService ..> CarProvidersID : <<ResourcePath>>\n/carproviders/:id
CarProvidersID ..> CarProvider

RenCService ..> Auth : <<ResourcePath>>\n/auth
Auth ..> User

RenCService ..> Rentals : <<ResourcePath>>\n/rental
Rentals ..> Rental

RenCService ..> RentalsID : <<ResourcePath>>\n/rental/:id
RentalsID ..> Rental

RenCService ..> Middleware

@enduml
