@startuml GET /carProviders
actor       Client       as client
participant ":server" as server 
participant "<<Router>>\n:carProviders" as carProviders_router 
participant "<<Middleware>>\n:middleware" as middleware 
participant "<<Controller>>\n:carProviders" as carProviders_con 
participant "<<Model>>\n:carProvider" as carProviders_model 
database Database as db

client -> server : GET /carProviders

server -> carProviders_router : app.use("/carProviders", carProviders)
carProviders_router -> middleware : protect 
middleware -> carProviders_con : getCarProviders
activate carProviders_con
    carProviders_con -> carProviders_model : find()
    activate carProviders_model
    carProviders_model -> db : CarProviderSchema
        activate db
        db --> carProviders_model : carProviders
        deactivate db
    carProviders_model --> carProviders_con : carProviders
    deactivate carProviders_model

carProviders_con -> client :respond
deactivate carProviders_con
@enduml