@startuml POST /carProviders
actor       Client       as client
participant ":server" as server 
participant "<<Router>>\n:carProviders" as carProviders_router 
participant "<<Middleware>>\n:middleware" as middleware 
participant "<<Controller>>\n:carProviders" as carProviders_con 
participant "<<Model>>\n:carProvider" as carProviders_model 
database Database as db

client -> server : POST /carProviders

server -> carProviders_router : app.use("/carProviders", carProviders)
carProviders_router -> middleware : protect 
middleware -> middleware : authorize('admin')
middleware -> carProviders_con : createCarProvider
activate carProviders_con
    carProviders_con -> carProviders_model : create(req.body)
    activate carProviders_model
    carProviders_model -> db : CarProviderSchema
        activate db
        db --> carProviders_model : carProvider
        deactivate db
    carProviders_model --> carProviders_con : carProvider
    deactivate carProviders_model

carProviders_con -> client :respond
deactivate carProviders_con

@enduml