@startuml GET /rentals/:id
actor       Client       as client
participant ":server" as server 
participant "<<Router>>\n:rentals" as rentals_router 
participant "<<Middleware>>\n:middleware" as middleware 
participant "<<Controller>>\n:rentals" as rentals_con 
participant "<<Model>>\n:Rental" as rentals_model 
database Database as db

client -> server : GET /rentals/:id
server -> rentals_router : app.use("/rentals/:id", rentals)
rentals_router -> middleware : protect
middleware -> rentals_con : getRental
activate rentals_con
    rentals_con -> rentals_model : findById(req.params.id).populate('carProvider')
    activate rentals_model
    rentals_model -> db : RentalSchema
        activate db
        db --> rentals_model : rental
        deactivate db
    rentals_model --> rentals_con : rental
    deactivate rentals_model

rentals_con --> client :respond
deactivate rentals_con
@enduml