@startuml POST /rentals/:rentalId/rentals
actor       Client       as client
participant ":server" as server 
participant "<<Router>>\n:rentals" as rentals_router 
participant "<<Middleware>>\n:middleware" as middleware 
participant "<<Controller>>\n:rentals" as rentals_con
participant "<<Model>>\n:carProvider" as carProviders_model 
participant "<<Model>>\n:rental" as rentals_model 
database Database as db

client -> server : POST /rentals
server -> rentals_router : app.use("/rentals")
rentals_router -> middleware : protect
middleware -> middleware : authorize('admin', 'user')
middleware -> rentals_con : addRental
activate rentals_con
    
    rentals_con -> rentals_model : create(req.body)
    activate rentals_model
    rentals_model -> db : RentalSchema
        activate db
        db --> rentals_model : rental
        deactivate db
    rentals_model --> rentals_con : rental
    deactivate rentals_model

rentals_con --> client :respond
deactivate rentals_con


@enduml