@startuml PUT /rentals/:id
actor       Client       as client
participant ":server" as server
participant "<<Router>>\n:rentals" as rentals_router 
participant "<<Middleware>>\n:middleware" as middleware 
participant "<<Controller>>\n:rentals" as rentals_con 
participant "<<Model>>\n:rental" as rentals_model 
database Database as db

client -> server : PUT /rentals/:id

server -> rentals_router : app.use("/rentals/:id", rentals)
rentals_router -> middleware : protect
middleware -> middleware : authorize('admin', 'user')
middleware -> rentals_con : updateRental

activate rentals_con
    rentals_con -> rentals_model : findByIdAndUpdate(req.params.id, req.body)
    activate rentals_model
    rentals_model -> db : RentalSchema
        activate db
        db --> rentals_model : rental
        deactivate db
    rentals_model --> rentals_con : rental
    deactivate rentals_model

rentals_con --> client :respond
deactivate rentals_con

@enduml